#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
# A Namespace for a single KafkaProxy instance
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
# A Namespace for a single KafkaProxy instance
apiVersion: v1
kind: Namespace
metadata:
  name: kroxylicious