#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-certificate
  namespace: kroxylicious
spec:
  isCA: true
  commonName: mycluster-proxy.kafka
  secretName: kroxy-server-key-material
  privateKey:
    algorithm: RSA
    size: 4096
    # Note the cert-manager default is PKCS1. The tls.key generated won't work with Kroxylicious unless you put
    # Bouncy Castle in the classpath.  PKCS8 works without the classpath addition.
    encoding: PKCS8
  dnsNames:
    - my-proxy-bootstrap.$$INGRESS_DOMAIN$$
    - my-proxy-broker-0.$$INGRESS_DOMAIN$$
    - my-proxy-broker-1.$$INGRESS_DOMAIN$$
    - my-proxy-broker-2.$$INGRESS_DOMAIN$$
  usages:
    - server auth
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
