#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kroxylicious-config
  namespace: kroxylicious
data:
  config.yaml: |
    adminHttp:
      endpoints:
        prometheus: {}
    virtualClusters:
      my-cluster-proxy:
        targetCluster:
          bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
          tls:
            trust:
              storeFile: /opt/kroxylicious/trust/ca.p12
              storePassword:
                passwordFile: /opt/kroxylicious/trust/ca.password
        clusterNetworkAddressConfigProvider:
          type: SniRoutingClusterNetworkAddressConfigProvider
          config:
            bootstrapAddress: my-proxy-bootstrap.$$INGRESS_DOMAIN$$:9092
            advertisedBrokerAddressPattern: my-proxy-broker-$(nodeId).$$INGRESS_DOMAIN$$:443
        logNetwork: false
        logFrames: false
        tls:
          key:
            privateKeyFile: /opt/kroxylicious/server/key-material/tls.key
            certificateFile: /opt/kroxylicious/server/key-material/tls.crt
